/**
 *
 *  DataStatistics.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace stufbsys
{

class DataStatistics
{
  public:
    struct Cols
    {
        static const std::string _visit;
        static const std::string _suggestion_num;
        static const std::string _evaluate_num;
        static const std::string _week;
        static const std::string _date;
        static const std::string _data_id;
        static const std::string _dish_add_num;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = short;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit DataStatistics(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit DataStatistics(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    DataStatistics(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    DataStatistics() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column visit  */
    ///Get the value of the column visit, returns the default value if the column is null
    const int32_t &getValueOfVisit() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getVisit() const noexcept;
    ///Set the value of the column visit
    void setVisit(const int32_t &pVisit) noexcept;
    void setVisitToNull() noexcept;

    /**  For column suggestion_num  */
    ///Get the value of the column suggestion_num, returns the default value if the column is null
    const int32_t &getValueOfSuggestionNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSuggestionNum() const noexcept;
    ///Set the value of the column suggestion_num
    void setSuggestionNum(const int32_t &pSuggestionNum) noexcept;
    void setSuggestionNumToNull() noexcept;

    /**  For column evaluate_num  */
    ///Get the value of the column evaluate_num, returns the default value if the column is null
    const int32_t &getValueOfEvaluateNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEvaluateNum() const noexcept;
    ///Set the value of the column evaluate_num
    void setEvaluateNum(const int32_t &pEvaluateNum) noexcept;
    void setEvaluateNumToNull() noexcept;

    /**  For column week  */
    ///Get the value of the column week, returns the default value if the column is null
    const std::string &getValueOfWeek() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWeek() const noexcept;
    ///Set the value of the column week
    void setWeek(const std::string &pWeek) noexcept;
    void setWeek(std::string &&pWeek) noexcept;
    void setWeekToNull() noexcept;

    /**  For column date  */
    ///Get the value of the column date, returns the default value if the column is null
    const ::trantor::Date &getValueOfDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDate() const noexcept;
    ///Set the value of the column date
    void setDate(const ::trantor::Date &pDate) noexcept;

    /**  For column data_id  */
    ///Get the value of the column data_id, returns the default value if the column is null
    const short &getValueOfDataId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<short> &getDataId() const noexcept;
    ///Set the value of the column data_id
    void setDataId(const short &pDataId) noexcept;

    /**  For column dish_add_num  */
    ///Get the value of the column dish_add_num, returns the default value if the column is null
    const int32_t &getValueOfDishAddNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getDishAddNum() const noexcept;
    ///Set the value of the column dish_add_num
    void setDishAddNum(const int32_t &pDishAddNum) noexcept;
    void setDishAddNumToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<DataStatistics>;
    friend drogon::orm::BaseBuilder<DataStatistics, true, true>;
    friend drogon::orm::BaseBuilder<DataStatistics, true, false>;
    friend drogon::orm::BaseBuilder<DataStatistics, false, true>;
    friend drogon::orm::BaseBuilder<DataStatistics, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<DataStatistics>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> visit_;
    std::shared_ptr<int32_t> suggestionNum_;
    std::shared_ptr<int32_t> evaluateNum_;
    std::shared_ptr<std::string> week_;
    std::shared_ptr<::trantor::Date> date_;
    std::shared_ptr<short> dataId_;
    std::shared_ptr<int32_t> dishAddNum_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where data_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where data_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        sql += "visit,";
        ++parametersCount;
        if(!dirtyFlag_[0])
        {
            needSelection=true;
        }
        sql += "suggestion_num,";
        ++parametersCount;
        if(!dirtyFlag_[1])
        {
            needSelection=true;
        }
        sql += "evaluate_num,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        if(dirtyFlag_[3])
        {
            sql += "week,";
            ++parametersCount;
        }
        sql += "date,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
            sql += "data_id,";
            ++parametersCount;
        sql += "dish_add_num,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        sql +="default,";
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace stufbsys
} // namespace drogon_model
