/**
 *
 *  DishEvaluate.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "DishEvaluate.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::stufbsys;

const std::string DishEvaluate::Cols::_evaluate_id = "\"evaluate_id\"";
const std::string DishEvaluate::Cols::_dish_id = "\"dish_id\"";
const std::string DishEvaluate::Cols::_user_id = "\"user_id\"";
const std::string DishEvaluate::Cols::_score = "\"score\"";
const std::string DishEvaluate::Cols::_evaluate_text = "\"evaluate_text\"";
const std::string DishEvaluate::Cols::_vote_count = "\"vote_count\"";
const std::string DishEvaluate::Cols::_date = "\"date\"";
const std::string DishEvaluate::primaryKeyName = "evaluate_id";
const bool DishEvaluate::hasPrimaryKey = true;
const std::string DishEvaluate::tableName = "\"dish_evaluate\"";

const std::vector<typename DishEvaluate::MetaData> DishEvaluate::metaData_={
{"evaluate_id","int64_t","bigint",8,1,1,1},
{"dish_id","int64_t","bigint",8,0,0,1},
{"user_id","int64_t","bigint",8,0,0,1},
{"score","short","smallint",2,0,0,1},
{"evaluate_text","std::string","character varying",255,0,0,0},
{"vote_count","int32_t","integer",4,0,0,0},
{"date","::trantor::Date","date",0,0,0,1}
};
const std::string &DishEvaluate::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
DishEvaluate::DishEvaluate(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["evaluate_id"].isNull())
        {
            evaluateId_=std::make_shared<int64_t>(r["evaluate_id"].as<int64_t>());
        }
        if(!r["dish_id"].isNull())
        {
            dishId_=std::make_shared<int64_t>(r["dish_id"].as<int64_t>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>(r["user_id"].as<int64_t>());
        }
        if(!r["score"].isNull())
        {
            score_=std::make_shared<short>(r["score"].as<short>());
        }
        if(!r["evaluate_text"].isNull())
        {
            evaluateText_=std::make_shared<std::string>(r["evaluate_text"].as<std::string>());
        }
        if(!r["vote_count"].isNull())
        {
            voteCount_=std::make_shared<int32_t>(r["vote_count"].as<int32_t>());
        }
        if(!r["date"].isNull())
        {
            auto daysStr = r["date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 7 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            evaluateId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            dishId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            score_=std::make_shared<short>(r[index].as<short>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            evaluateText_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            voteCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }

}

DishEvaluate::DishEvaluate(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            evaluateId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            dishId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            score_=std::make_shared<short>((short)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            evaluateText_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            voteCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

DishEvaluate::DishEvaluate(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("evaluate_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["evaluate_id"].isNull())
        {
            evaluateId_=std::make_shared<int64_t>((int64_t)pJson["evaluate_id"].asInt64());
        }
    }
    if(pJson.isMember("dish_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["dish_id"].isNull())
        {
            dishId_=std::make_shared<int64_t>((int64_t)pJson["dish_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("score"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["score"].isNull())
        {
            score_=std::make_shared<short>((short)pJson["score"].asInt64());
        }
    }
    if(pJson.isMember("evaluate_text"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["evaluate_text"].isNull())
        {
            evaluateText_=std::make_shared<std::string>(pJson["evaluate_text"].asString());
        }
    }
    if(pJson.isMember("vote_count"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["vote_count"].isNull())
        {
            voteCount_=std::make_shared<int32_t>((int32_t)pJson["vote_count"].asInt64());
        }
    }
    if(pJson.isMember("date"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["date"].isNull())
        {
            auto daysStr = pJson["date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void DishEvaluate::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 7)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            evaluateId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            dishId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            score_=std::make_shared<short>((short)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            evaluateText_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            voteCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

void DishEvaluate::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("evaluate_id"))
    {
        if(!pJson["evaluate_id"].isNull())
        {
            evaluateId_=std::make_shared<int64_t>((int64_t)pJson["evaluate_id"].asInt64());
        }
    }
    if(pJson.isMember("dish_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["dish_id"].isNull())
        {
            dishId_=std::make_shared<int64_t>((int64_t)pJson["dish_id"].asInt64());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<int64_t>((int64_t)pJson["user_id"].asInt64());
        }
    }
    if(pJson.isMember("score"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["score"].isNull())
        {
            score_=std::make_shared<short>((short)pJson["score"].asInt64());
        }
    }
    if(pJson.isMember("evaluate_text"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["evaluate_text"].isNull())
        {
            evaluateText_=std::make_shared<std::string>(pJson["evaluate_text"].asString());
        }
    }
    if(pJson.isMember("vote_count"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["vote_count"].isNull())
        {
            voteCount_=std::make_shared<int32_t>((int32_t)pJson["vote_count"].asInt64());
        }
    }
    if(pJson.isMember("date"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["date"].isNull())
        {
            auto daysStr = pJson["date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            date_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
}

const int64_t &DishEvaluate::getValueOfEvaluateId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(evaluateId_)
        return *evaluateId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &DishEvaluate::getEvaluateId() const noexcept
{
    return evaluateId_;
}
void DishEvaluate::setEvaluateId(const int64_t &pEvaluateId) noexcept
{
    evaluateId_ = std::make_shared<int64_t>(pEvaluateId);
    dirtyFlag_[0] = true;
}
const typename DishEvaluate::PrimaryKeyType & DishEvaluate::getPrimaryKey() const
{
    assert(evaluateId_);
    return *evaluateId_;
}

const int64_t &DishEvaluate::getValueOfDishId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(dishId_)
        return *dishId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &DishEvaluate::getDishId() const noexcept
{
    return dishId_;
}
void DishEvaluate::setDishId(const int64_t &pDishId) noexcept
{
    dishId_ = std::make_shared<int64_t>(pDishId);
    dirtyFlag_[1] = true;
}

const int64_t &DishEvaluate::getValueOfUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &DishEvaluate::getUserId() const noexcept
{
    return userId_;
}
void DishEvaluate::setUserId(const int64_t &pUserId) noexcept
{
    userId_ = std::make_shared<int64_t>(pUserId);
    dirtyFlag_[2] = true;
}

const short &DishEvaluate::getValueOfScore() const noexcept
{
    static const short defaultValue = short();
    if(score_)
        return *score_;
    return defaultValue;
}
const std::shared_ptr<short> &DishEvaluate::getScore() const noexcept
{
    return score_;
}
void DishEvaluate::setScore(const short &pScore) noexcept
{
    score_ = std::make_shared<short>(pScore);
    dirtyFlag_[3] = true;
}

const std::string &DishEvaluate::getValueOfEvaluateText() const noexcept
{
    static const std::string defaultValue = std::string();
    if(evaluateText_)
        return *evaluateText_;
    return defaultValue;
}
const std::shared_ptr<std::string> &DishEvaluate::getEvaluateText() const noexcept
{
    return evaluateText_;
}
void DishEvaluate::setEvaluateText(const std::string &pEvaluateText) noexcept
{
    evaluateText_ = std::make_shared<std::string>(pEvaluateText);
    dirtyFlag_[4] = true;
}
void DishEvaluate::setEvaluateText(std::string &&pEvaluateText) noexcept
{
    evaluateText_ = std::make_shared<std::string>(std::move(pEvaluateText));
    dirtyFlag_[4] = true;
}
void DishEvaluate::setEvaluateTextToNull() noexcept
{
    evaluateText_.reset();
    dirtyFlag_[4] = true;
}

const int32_t &DishEvaluate::getValueOfVoteCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(voteCount_)
        return *voteCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &DishEvaluate::getVoteCount() const noexcept
{
    return voteCount_;
}
void DishEvaluate::setVoteCount(const int32_t &pVoteCount) noexcept
{
    voteCount_ = std::make_shared<int32_t>(pVoteCount);
    dirtyFlag_[5] = true;
}
void DishEvaluate::setVoteCountToNull() noexcept
{
    voteCount_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &DishEvaluate::getValueOfDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(date_)
        return *date_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &DishEvaluate::getDate() const noexcept
{
    return date_;
}
void DishEvaluate::setDate(const ::trantor::Date &pDate) noexcept
{
    date_ = std::make_shared<::trantor::Date>(pDate.roundDay());
    dirtyFlag_[6] = true;
}

void DishEvaluate::updateId(const uint64_t id)
{
}

const std::vector<std::string> &DishEvaluate::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "dish_id",
        "user_id",
        "score",
        "evaluate_text",
        "vote_count",
        "date"
    };
    return inCols;
}

void DishEvaluate::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDishId())
        {
            binder << getValueOfDishId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScore())
        {
            binder << getValueOfScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEvaluateText())
        {
            binder << getValueOfEvaluateText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getVoteCount())
        {
            binder << getValueOfVoteCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDate())
        {
            binder << getValueOfDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> DishEvaluate::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    return ret;
}

void DishEvaluate::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getDishId())
        {
            binder << getValueOfDishId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScore())
        {
            binder << getValueOfScore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEvaluateText())
        {
            binder << getValueOfEvaluateText();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getVoteCount())
        {
            binder << getValueOfVoteCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDate())
        {
            binder << getValueOfDate();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value DishEvaluate::toJson() const
{
    Json::Value ret;
    if(getEvaluateId())
    {
        ret["evaluate_id"]=(Json::Int64)getValueOfEvaluateId();
    }
    else
    {
        ret["evaluate_id"]=Json::Value();
    }
    if(getDishId())
    {
        ret["dish_id"]=(Json::Int64)getValueOfDishId();
    }
    else
    {
        ret["dish_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScore())
    {
        ret["score"]=getValueOfScore();
    }
    else
    {
        ret["score"]=Json::Value();
    }
    if(getEvaluateText())
    {
        ret["evaluate_text"]=getValueOfEvaluateText();
    }
    else
    {
        ret["evaluate_text"]=Json::Value();
    }
    if(getVoteCount())
    {
        ret["vote_count"]=getValueOfVoteCount();
    }
    else
    {
        ret["vote_count"]=Json::Value();
    }
    if(getDate())
    {
        ret["date"]=getDate()->toDbStringLocal();
    }
    else
    {
        ret["date"]=Json::Value();
    }
    return ret;
}

Json::Value DishEvaluate::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 7)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getEvaluateId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfEvaluateId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getDishId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfDishId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getScore())
            {
                ret[pMasqueradingVector[3]]=getValueOfScore();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEvaluateText())
            {
                ret[pMasqueradingVector[4]]=getValueOfEvaluateText();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getVoteCount())
            {
                ret[pMasqueradingVector[5]]=getValueOfVoteCount();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getDate())
            {
                ret[pMasqueradingVector[6]]=getDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getEvaluateId())
    {
        ret["evaluate_id"]=(Json::Int64)getValueOfEvaluateId();
    }
    else
    {
        ret["evaluate_id"]=Json::Value();
    }
    if(getDishId())
    {
        ret["dish_id"]=(Json::Int64)getValueOfDishId();
    }
    else
    {
        ret["dish_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=(Json::Int64)getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScore())
    {
        ret["score"]=getValueOfScore();
    }
    else
    {
        ret["score"]=Json::Value();
    }
    if(getEvaluateText())
    {
        ret["evaluate_text"]=getValueOfEvaluateText();
    }
    else
    {
        ret["evaluate_text"]=Json::Value();
    }
    if(getVoteCount())
    {
        ret["vote_count"]=getValueOfVoteCount();
    }
    else
    {
        ret["vote_count"]=Json::Value();
    }
    if(getDate())
    {
        ret["date"]=getDate()->toDbStringLocal();
    }
    else
    {
        ret["date"]=Json::Value();
    }
    return ret;
}

bool DishEvaluate::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("evaluate_id"))
    {
        if(!validJsonOfField(0, "evaluate_id", pJson["evaluate_id"], err, true))
            return false;
    }
    if(pJson.isMember("dish_id"))
    {
        if(!validJsonOfField(1, "dish_id", pJson["dish_id"], err, true))
            return false;
    }
    else
    {
        err="The dish_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    else
    {
        err="The user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("score"))
    {
        if(!validJsonOfField(3, "score", pJson["score"], err, true))
            return false;
    }
    else
    {
        err="The score column cannot be null";
        return false;
    }
    if(pJson.isMember("evaluate_text"))
    {
        if(!validJsonOfField(4, "evaluate_text", pJson["evaluate_text"], err, true))
            return false;
    }
    if(pJson.isMember("vote_count"))
    {
        if(!validJsonOfField(5, "vote_count", pJson["vote_count"], err, true))
            return false;
    }
    if(pJson.isMember("date"))
    {
        if(!validJsonOfField(6, "date", pJson["date"], err, true))
            return false;
    }
    return true;
}
bool DishEvaluate::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DishEvaluate::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("evaluate_id"))
    {
        if(!validJsonOfField(0, "evaluate_id", pJson["evaluate_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("dish_id"))
    {
        if(!validJsonOfField(1, "dish_id", pJson["dish_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("score"))
    {
        if(!validJsonOfField(3, "score", pJson["score"], err, false))
            return false;
    }
    if(pJson.isMember("evaluate_text"))
    {
        if(!validJsonOfField(4, "evaluate_text", pJson["evaluate_text"], err, false))
            return false;
    }
    if(pJson.isMember("vote_count"))
    {
        if(!validJsonOfField(5, "vote_count", pJson["vote_count"], err, false))
            return false;
    }
    if(pJson.isMember("date"))
    {
        if(!validJsonOfField(6, "date", pJson["date"], err, false))
            return false;
    }
    return true;
}
bool DishEvaluate::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 7)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool DishEvaluate::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
