/**
 *
 *  TeacherDataStatistics.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace stufbsys
{

class TeacherDataStatistics
{
  public:
    struct Cols
    {
        static const std::string _data_id;
        static const std::string _visit;
        static const std::string _teacher_all_suggestion_num;
        static const std::string _teacher_suggestion_num;
        static const std::string _teacher_vote_num;
        static const std::string _teacher_id;
        static const std::string _week;
        static const std::string _date;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit TeacherDataStatistics(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit TeacherDataStatistics(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    TeacherDataStatistics(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    TeacherDataStatistics() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column data_id  */
    ///Get the value of the column data_id, returns the default value if the column is null
    const int64_t &getValueOfDataId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getDataId() const noexcept;
    ///Set the value of the column data_id
    void setDataId(const int64_t &pDataId) noexcept;

    /**  For column visit  */
    ///Get the value of the column visit, returns the default value if the column is null
    const int32_t &getValueOfVisit() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getVisit() const noexcept;
    ///Set the value of the column visit
    void setVisit(const int32_t &pVisit) noexcept;
    void setVisitToNull() noexcept;

    /**  For column teacher_all_suggestion_num  */
    ///Get the value of the column teacher_all_suggestion_num, returns the default value if the column is null
    const int32_t &getValueOfTeacherAllSuggestionNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTeacherAllSuggestionNum() const noexcept;
    ///Set the value of the column teacher_all_suggestion_num
    void setTeacherAllSuggestionNum(const int32_t &pTeacherAllSuggestionNum) noexcept;
    void setTeacherAllSuggestionNumToNull() noexcept;

    /**  For column teacher_suggestion_num  */
    ///Get the value of the column teacher_suggestion_num, returns the default value if the column is null
    const int32_t &getValueOfTeacherSuggestionNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTeacherSuggestionNum() const noexcept;
    ///Set the value of the column teacher_suggestion_num
    void setTeacherSuggestionNum(const int32_t &pTeacherSuggestionNum) noexcept;
    void setTeacherSuggestionNumToNull() noexcept;

    /**  For column teacher_vote_num  */
    ///Get the value of the column teacher_vote_num, returns the default value if the column is null
    const int32_t &getValueOfTeacherVoteNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getTeacherVoteNum() const noexcept;
    ///Set the value of the column teacher_vote_num
    void setTeacherVoteNum(const int32_t &pTeacherVoteNum) noexcept;
    void setTeacherVoteNumToNull() noexcept;

    /**  For column teacher_id  */
    ///Get the value of the column teacher_id, returns the default value if the column is null
    const int64_t &getValueOfTeacherId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getTeacherId() const noexcept;
    ///Set the value of the column teacher_id
    void setTeacherId(const int64_t &pTeacherId) noexcept;
    void setTeacherIdToNull() noexcept;

    /**  For column week  */
    ///Get the value of the column week, returns the default value if the column is null
    const std::string &getValueOfWeek() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWeek() const noexcept;
    ///Set the value of the column week
    void setWeek(const std::string &pWeek) noexcept;
    void setWeek(std::string &&pWeek) noexcept;
    void setWeekToNull() noexcept;

    /**  For column date  */
    ///Get the value of the column date, returns the default value if the column is null
    const ::trantor::Date &getValueOfDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDate() const noexcept;
    ///Set the value of the column date
    void setDate(const ::trantor::Date &pDate) noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<TeacherDataStatistics>;
    friend drogon::orm::BaseBuilder<TeacherDataStatistics, true, true>;
    friend drogon::orm::BaseBuilder<TeacherDataStatistics, true, false>;
    friend drogon::orm::BaseBuilder<TeacherDataStatistics, false, true>;
    friend drogon::orm::BaseBuilder<TeacherDataStatistics, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<TeacherDataStatistics>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> dataId_;
    std::shared_ptr<int32_t> visit_;
    std::shared_ptr<int32_t> teacherAllSuggestionNum_;
    std::shared_ptr<int32_t> teacherSuggestionNum_;
    std::shared_ptr<int32_t> teacherVoteNum_;
    std::shared_ptr<int64_t> teacherId_;
    std::shared_ptr<std::string> week_;
    std::shared_ptr<::trantor::Date> date_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where data_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where data_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "data_id,";
            ++parametersCount;
        sql += "visit,";
        ++parametersCount;
        if(!dirtyFlag_[1])
        {
            needSelection=true;
        }
        sql += "teacher_all_suggestion_num,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        sql += "teacher_suggestion_num,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        sql += "teacher_vote_num,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "teacher_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "week,";
            ++parametersCount;
        }
        sql += "date,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace stufbsys
} // namespace drogon_model
